### PR TITLE
Add support for Symfony 6.0

### PR DESCRIPTION
**Pull request by jderusse**
:crossed_fingers:

### CODE REVIEW

**Review by dunglas — APPROVED** [review]

**Comment by mhpcc** [comment]
This wouldn't work as symfony 6 specifies return types for several methods, in turn requiring this bundle to add them too.

Method "Symfony\Component\Serializer\Normalizer\NormalizerInterface::normalize()" might add "array|string|int|float|bool|\ArrayObject|null" as a native return type declaration in the future. Do the same in implementation "Dunglas\DoctrineJsonOdm\Serializer" now to avoid errors or add an explicit @return annotation to suppress this message.

Method "Symfony\Component\Serializer\Normalizer\DenormalizerInterface::denormalize()" might add "mixed" as a native return type declaration in the future. Do the same in implementation "Dunglas\DoctrineJsonOdm\Serializer" now to avoid errors or add an explicit @return annotation to suppress this message.

**Comment by jderusse** [comment]
Bumped to 6.0.1 to fix the issue Normalizer signature issue

**Comment by dunglas** [comment]
Thanks @jderusse! I'll try to tag a release soon (but probably after or during SymfonyWorld).

**Comment by mhpcc** [comment]
@dunglas symfony apparently keeps the function signature of normalize(): array|string|int|float|bool|\ArrayObject|null as visible in https://github.com/symfony/serializer/blob/6.0/Serializer.php

**Pull request merged**
