### PR TITLE
Release 1.0.0

### PR DESCRIPTION
**Pull request by Toflar**

### CODE REVIEW

**Comment by Toflar** [comment]
@ajgarlag can I ask you to read through the README once again too? Especially double checking the way custom normalizers are registered etc.

**Comment by Toflar** [comment]
@dunglas there's a not in the README saying

> All PHP objects and structures will be preserved (if you use Symfony >= 3.1, see the FAQ).

But there's no such part in the FAQ. And I wonder if we should still support < 3.4. The only remaining, supported version is 2.8 and it's only for maybe another 4 months. Personally, I'd be fine raising the minimum required version to 3.4 and removing that README info then :)

**Comment by ajgarlag** [comment]
The README LGTM

If you drop support for symfony < 3.4, you should revert all changes to `src/Bundle/DependencyInjection/DunglasDoctrineJsonOdmExtension.php` from #71

**Comment by Toflar** [comment]
Yes, thanks for the reminder.

**Comment by ajgarlag** [comment]
What do you think about skipping functional test if we cannot connect with database? It allowed me to run tests from local machine. If you think it's valuable, I can open a PR.

 See https://github.com/ajgarlag/doctrine-json-odm/commit/5cd6d7c2486495b4a2e29feb4e0a98679f50f72

**Comment by Toflar** [comment]
So I've raised the minimum version to 3.4 and did some cleanup in the tests. `1.0.0-rc1` is released now, go ahead and test 😄

**Pull request merged**
