### PR TITLE
Bump minimum deps compatibility

### PR DESCRIPTION
**Pull request by amenophis**
This PR remove compatibility with php < 8.1 and symfony < 5.4.
It also add compatibility with symfony 7.0

### CODE REVIEW

**Comment by amenophis** [comment]
@dunglas Don't know why i have to add the dependency on symfony/validator, any idea ?

**Comment by dunglas** [comment]
That's likely a bug (a missing `class_exists()` in Symfony).

**Comment by back-2-95** [comment]
Is there some Symfony issue which this is waiting?

**Comment by dunglas** [comment]
Thank you @amenophis!!

**Pull request merged**
