### PR TITLE
Add Uid normalizer

### PR DESCRIPTION
**Pull request by amenophis**
This PR add the Symfony Uid normalizer

### CODE REVIEW

**Comment by amenophis** [comment]
@dunglas Do you know how i can handle the installation for symfony/uid only for php >= 7.2 ?

Thanks :pray:

**Comment by dunglas** [comment]
You can either bump the minimum PHP version (PHP <8 isn't maintained anymore) or install `symfony/uid` only in the CI workflows when PHP >= 7.2.

**Comment by amenophis** [comment]
Are you OK with removing compatibility with  < 8 ?

**Comment by amenophis** [comment]
@dunglas With symfony 7.0 release, the CI was broken, are you OK to revert 7.0 support now ? I will send a new PR with a complete support

**Comment by dunglas** [comment]
Yes, no problem

**Comment by amenophis** [comment]
The PR is ready, ok for merge ?

**Review by dunglas — APPROVED** [review]

**Comment by dunglas** [comment]
Thank you!!

**Comment by back-2-95** [comment]
@amenophis were you planning to do that new PR (bringing back SF7 support) or?

**Comment by amenophis** [comment]
@back-2-95 In progress here: https://github.com/dunglas/doctrine-json-odm/pull/133

**Pull request merged**
